### ISSUE TITLE
Long caching intervals

### ISSUE THREAD

**Issue by KnorpelSenf** [ydcjeff/shield.deno.dev#2]
### Describe the bug

When releasing a new version (creating a new tag on /x) the shield is outdated for a long time. Last time it took almost a week until it would update. This time it's been half an hour so far, and the change is still pending. Is there a way to force-update the badge? We publish dually on both npm and /x and it looks bad if the Deno version is always behind for days.

### Reproduction

Visit https://github.com/grammyjs/grammY and look at the shields. (If it depends on the location, I know that both Germany and Norway are affected.)

**SHIELDS**
[![Deno](https://shield.deno.dev/x/grammy)](https://deno.land/x/grammy) [![npm](https://img.shields.io/npm/v/grammy?logo=npm&style=flat&labelColor=000&color=3b82f6)](https://www.npmjs.org/package/grammy)

**AS RENDERED**
![image](https://user-images.githubusercontent.com/12952387/178256291-7302200b-714c-4a0e-b732-9d7f5f5f0fef.png)

**Comment by KnorpelSenf** [comment]
Note that `img.shields.io` sets a header `cache-control: max-age=300, s-maxage=300` but `shield.deno.dev` does not. I assume that GitHub caches the shields much longer if it is being allowed to.

**Comment by jeffydc** [comment]
@KnorpelSenf I have added the `cache-control` header, and FYI you can find how to purge the cache by GitHub on [GitHub docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#removing-an-image-from-camos-cache).

**Comment by KnorpelSenf** [comment]
Thank you so much!
