### ISSUE TITLE
provide `std` support

### ISSUE THREAD

**Issue by scarf005** [ydcjeff/shield.deno.dev#5]
### Clear and concise description of the problem

It's often useful to also list the std version it uses.

### Suggested solution

provide `shield.deno.dev/std/` for compatible std version.

### Alternative

using [![deno module](https://shield.deno.dev/x/std)](https://deno.land/x/std), however it displays as `deno.land/x` not `deno.land/std`.

### Additional context

I'm interested in opening a PR.

**Comment by jeffydc** [comment]
Sounds good!. PR welcome.
